### ISSUE TITLE
[Question] Unable to connect to MySQL DB from remote machine:mysql.connector.errors.DatabaseError: 1130 (HY000): Host 'machine.xxx.xxx.com' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by ovclara** [LuciferJack/python-mysql-pool#9]
I am new to this world so I do anything wrong please guide me.

I am using MySQL DB server 8.0 and trying to connect from a remote machine using below Python code:
`import mysql.connector
mydb = mysql.connector.connect(host='10.xx.xxx.xx', user='dummyuser', passwd='dummypwd')
myCursor = mydb.cursor()
myCursor.execute("show databases")
for i in myCursor:
    print(i)`

I get below error:
mysql.connector.errors.DatabaseError: 1130 (HY000): Host 'xxxxxx-xxx-xxx.xxx.xxx.com' is not allowed to connect to this MySQL server

I checked on the net but nothing seems to work for me can you please guide how can I get this resolved.

**Comment by stefanxyan** [comment]
收到邮件！

**Comment by ovclara** [comment]
Issue is Solved hence Closing it.
The Host name was replaced by %.%.%.%

**Comment by stefanxyan** [comment]
收到邮件！
